"""
Starts from the steady state generated by sim_is_steady.py. Reduces melt
over a month with sliding and conductivity fixed. 
"""

from dolfin import *
from dolfin import MPI, mpi_comm_world
from sheet_model import *
from constants import *

# Process number
MPI_rank = MPI.rank(mpi_comm_world())
# Output directory
out_dir = 'out_is_winter_realistic'
# Input file
input_file = 'inputs/inputs_is_steady.hdf5'


### Initialize model

model_inputs = {}
model_inputs['input_file'] = input_file
model_inputs['out_dir'] = out_dir
model = SheetModel(model_inputs)


m = Function(model.V_cg)
m.assign(model.m)
u_b = Function(model.V_cg)
u_b.assign(model.u_b)

# Seconds per day
spd = pcs['spd']
# Seconds per year
spy = pcs['spy']
# How long it takes for the melt to shut off completely
shutoff_length = 30.0 * spd
 
# Function that reduces melt to 0 over time
def m_scale(t):
  if t < 0.0:
    return 1.0
  if t <= shutoff_length:
    return cos((pi / (2.0 * shutoff_length)) * t)
  return 0.0

# Minimum conductivity
k_min = 5e-5
# Scaling parameter ensures that sets the maximum possible conductivity
a = model.pcs['k'] / m.vector().max()
# Parameter that controls lag of conductivity behind melt
b = 0.0
# Function that scales k proportionally to m
def k_scale(t):
  return a * m_scale(t - b)
  
# Create a function that scales u_b down to a maximum of 80 (m/a) in winter
c = (100.0 / pcs['spy']) / u_b.vector().max()
def u_b_scale(t):
  return -m_scale(t) * (c - 1.0) + c


### Run the simulation

# Seconds per day
spd = pcs['spd']
# Seconds per month
spm = pcs['spm']
# End time
T = 10.0 * spm
# Time step
dt = 60.0 * 60.0 * 8.0
# Iteration count
i = 0

while model.t < T:  
  
  # Update the melt
  model.set_m(project(Constant(m_scale(model.t)) * m, V_cg))
  # Update the conductivity
  model.set_k(project(Constant(k_scale(model.t)) * m + Constant(k_min), V_cg))
  # Update the sliding speed
  model.set_u_b(project(Constant(u_b_scale(model.t)) * u_b, V_cg))  
  
  if MPI_rank == 0: 
    current_time = model.t / spd
    print ('%sCurrent time: %s %s' % (fg(1), current_time, attr(0)))
  
  model.step(dt)
  
  if i % 3 == 0:
    model.write_pvds(['h', 'pfo'])
    
  if i % 3 == 0:
    model.checkpoint(['pfo', 'h', 'k', 'm', 'u_b'])
  
  if MPI_rank == 0: 
    print
    
  i += 1
